//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramewokTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriterioAceptación
    {
        public int IdCriterioAceptacion { get; set; }
        public string NomCriterioAceptacion { get; set; }
        public bool EstadoCriterioAceptacion { get; set; }
    
        public virtual Entregable Entregable { get; set; }
    }
}
