//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramewokTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSIT_ObligacionesEntities : DbContext
    {
        public CSIT_ObligacionesEntities()
            : base("name=CSIT_ObligacionesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Anexo> Anexo { get; set; }
        public virtual DbSet<Capitulo> Capitulo { get; set; }
        public virtual DbSet<CriterioAceptación> CriterioAceptación { get; set; }
        public virtual DbSet<Cumplimiento> Cumplimiento { get; set; }
        public virtual DbSet<Entregable> Entregable { get; set; }
        public virtual DbSet<Obligacion> Obligacion { get; set; }
        public virtual DbSet<Periodicidad> Periodicidad { get; set; }
        public virtual DbSet<Seguimiento> Seguimiento { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
