//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramewokTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguimiento
    {
        public int IdSeguimiento { get; set; }
        public int IdObligación { get; set; }
        public int IdCumplimiento { get; set; }
        public System.DateTime FechaSeguimiento { get; set; }
        public string ObservacionSeguimiento { get; set; }
        public string LinkEvidencia { get; set; }
    
        public virtual Cumplimiento Cumplimiento { get; set; }
        public virtual Obligacion Obligacion { get; set; }
    }
}
