//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Capitulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Capitulo()
        {
            this.Obligacion = new HashSet<Obligacion>();
        }
    
        public int IdCapitulo { get; set; }
        public string NomCapitulo { get; set; }
        public bool EstadoCapitulo { get; set; }
        public Nullable<int> IdAnexo { get; set; }
    
        public virtual Anexo Anexo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obligacion> Obligacion { get; set; }

        public string Estado
        {
            get
            {
                string estado = string.Empty;
                if (EstadoCapitulo)
                    estado = "Activo";
                else
                    estado = "Inactivo";
                return estado;

            }
        }
    }
}
