//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entregable
    {
        public int IdEntregable { get; set; }
        public string NomEntregable { get; set; }
        public bool EstadoEntregable { get; set; }
        public int IdObligacion { get; set; }
        public int IdPeriodicidad { get; set; }
    
        public virtual CriterioAceptación CriterioAceptación { get; set; }
        public virtual Obligacion Obligacion { get; set; }
        public virtual Periodicidad Periodicidad { get; set; }
    }
}
